name: Mirror rolling to galactic-devel

on:
  push:
    branches: [ rolling ]

jobs:
  mirror-to-galactic-devel:
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      with:
        target-branch: galactic-devel
